### PR TITLE
Add Xcode 7.1 GM to DVTPlugInCompatibilityUUIDs

### PR DESCRIPTION
**Pull request by dppeak**

### CODE REVIEW

**Comment by zenangst** [comment]
@dppeak cheers :beers:

**Comment by onmyway133** [comment]
There should be a script that automates all of this Xcode UUIDs update stuff :]

**Comment by zenangst** [comment]
@onmyway133 that would be great!

**Comment by onmyway133** [comment]
@zenangst forget to mention that it is https://github.com/onmyway133/Minion :stuck_out_tongue_winking_eye:

**Comment by zenangst** [comment]
@onmyway133 awesome! I'll check it out! :grin:

**Pull request merged**
